title: Researcher
url: "https://imlixinyang.github.io"
baseurl: "/resume-cv"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #


sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/resume-cv/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
